name: repo-setup-aws
description: "Runs all baseline setup to interact with a AWS-hosted manager instance"

runs:
  using: "composite"
  steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS-ACCESS-KEY-ID }}
          aws-secret-access-key: ${{ env.AWS-SECRET-ACCESS-KEY }}
          aws-region: ${{ env.AWS-DEFAULT-REGION }}
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ env.FIRESIM_PEM }}
          known_hosts: unnecessary
      - uses: ./.github/actions/install-ci-python-reqs
