name: machinelaunchscript
description: "Run FireSim's machine-launch-script.sh. Used only for GH-hosted CI containers"

runs:
  using: "composite"
  steps:
    - run: |
        # Mark the github workspace as a safe directory so we can run arbitrary
        # git commands during build-setup.sh.
        # See https://github.blog/2022-04-12-git-security-vulnerability-announced/
        # and https://github.com/actions/checkout/issues/760 for the workaround
        git config --global --add safe.directory $(pwd)
        cd scripts/ && /usr/bin/bash machine-launch-script.sh
      shell: bash
